// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feedback.proto

package grpc;

public final class Feedback {
  private Feedback() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SaveFeedbackRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.SaveFeedbackRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string item_id = 1;</code>
     */
    java.lang.String getItemId();
    /**
     * <code>string item_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getItemIdBytes();

    /**
     * <code>int32 buyer_id = 2;</code>
     */
    int getBuyerId();

    /**
     * <code>bool feedback = 3;</code>
     */
    boolean getFeedback();
  }
  /**
   * Protobuf type {@code grpc.SaveFeedbackRequest}
   */
  public  static final class SaveFeedbackRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.SaveFeedbackRequest)
      SaveFeedbackRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveFeedbackRequest.newBuilder() to construct.
    private SaveFeedbackRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveFeedbackRequest() {
      itemId_ = "";
      buyerId_ = 0;
      feedback_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SaveFeedbackRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              itemId_ = s;
              break;
            }
            case 16: {

              buyerId_ = input.readInt32();
              break;
            }
            case 24: {

              feedback_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Feedback.internal_static_grpc_SaveFeedbackRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Feedback.internal_static_grpc_SaveFeedbackRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Feedback.SaveFeedbackRequest.class, grpc.Feedback.SaveFeedbackRequest.Builder.class);
    }

    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object itemId_;
    /**
     * <code>string item_id = 1;</code>
     */
    public java.lang.String getItemId() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemId_ = s;
        return s;
      }
    }
    /**
     * <code>string item_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUYER_ID_FIELD_NUMBER = 2;
    private int buyerId_;
    /**
     * <code>int32 buyer_id = 2;</code>
     */
    public int getBuyerId() {
      return buyerId_;
    }

    public static final int FEEDBACK_FIELD_NUMBER = 3;
    private boolean feedback_;
    /**
     * <code>bool feedback = 3;</code>
     */
    public boolean getFeedback() {
      return feedback_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getItemIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, itemId_);
      }
      if (buyerId_ != 0) {
        output.writeInt32(2, buyerId_);
      }
      if (feedback_ != false) {
        output.writeBool(3, feedback_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getItemIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, itemId_);
      }
      if (buyerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buyerId_);
      }
      if (feedback_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, feedback_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Feedback.SaveFeedbackRequest)) {
        return super.equals(obj);
      }
      grpc.Feedback.SaveFeedbackRequest other = (grpc.Feedback.SaveFeedbackRequest) obj;

      boolean result = true;
      result = result && getItemId()
          .equals(other.getItemId());
      result = result && (getBuyerId()
          == other.getBuyerId());
      result = result && (getFeedback()
          == other.getFeedback());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId().hashCode();
      hash = (37 * hash) + BUYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBuyerId();
      hash = (37 * hash) + FEEDBACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFeedback());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.SaveFeedbackRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Feedback.SaveFeedbackRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.SaveFeedbackRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.SaveFeedbackRequest)
        grpc.Feedback.SaveFeedbackRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Feedback.internal_static_grpc_SaveFeedbackRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Feedback.internal_static_grpc_SaveFeedbackRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Feedback.SaveFeedbackRequest.class, grpc.Feedback.SaveFeedbackRequest.Builder.class);
      }

      // Construct using grpc.Feedback.SaveFeedbackRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        itemId_ = "";

        buyerId_ = 0;

        feedback_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Feedback.internal_static_grpc_SaveFeedbackRequest_descriptor;
      }

      @java.lang.Override
      public grpc.Feedback.SaveFeedbackRequest getDefaultInstanceForType() {
        return grpc.Feedback.SaveFeedbackRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Feedback.SaveFeedbackRequest build() {
        grpc.Feedback.SaveFeedbackRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Feedback.SaveFeedbackRequest buildPartial() {
        grpc.Feedback.SaveFeedbackRequest result = new grpc.Feedback.SaveFeedbackRequest(this);
        result.itemId_ = itemId_;
        result.buyerId_ = buyerId_;
        result.feedback_ = feedback_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Feedback.SaveFeedbackRequest) {
          return mergeFrom((grpc.Feedback.SaveFeedbackRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Feedback.SaveFeedbackRequest other) {
        if (other == grpc.Feedback.SaveFeedbackRequest.getDefaultInstance()) return this;
        if (!other.getItemId().isEmpty()) {
          itemId_ = other.itemId_;
          onChanged();
        }
        if (other.getBuyerId() != 0) {
          setBuyerId(other.getBuyerId());
        }
        if (other.getFeedback() != false) {
          setFeedback(other.getFeedback());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Feedback.SaveFeedbackRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Feedback.SaveFeedbackRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object itemId_ = "";
      /**
       * <code>string item_id = 1;</code>
       */
      public java.lang.String getItemId() {
        java.lang.Object ref = itemId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getItemIdBytes() {
        java.lang.Object ref = itemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder setItemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = getDefaultInstance().getItemId();
        onChanged();
        return this;
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder setItemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itemId_ = value;
        onChanged();
        return this;
      }

      private int buyerId_ ;
      /**
       * <code>int32 buyer_id = 2;</code>
       */
      public int getBuyerId() {
        return buyerId_;
      }
      /**
       * <code>int32 buyer_id = 2;</code>
       */
      public Builder setBuyerId(int value) {
        
        buyerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buyer_id = 2;</code>
       */
      public Builder clearBuyerId() {
        
        buyerId_ = 0;
        onChanged();
        return this;
      }

      private boolean feedback_ ;
      /**
       * <code>bool feedback = 3;</code>
       */
      public boolean getFeedback() {
        return feedback_;
      }
      /**
       * <code>bool feedback = 3;</code>
       */
      public Builder setFeedback(boolean value) {
        
        feedback_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool feedback = 3;</code>
       */
      public Builder clearFeedback() {
        
        feedback_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.SaveFeedbackRequest)
    }

    // @@protoc_insertion_point(class_scope:grpc.SaveFeedbackRequest)
    private static final grpc.Feedback.SaveFeedbackRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Feedback.SaveFeedbackRequest();
    }

    public static grpc.Feedback.SaveFeedbackRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveFeedbackRequest>
        PARSER = new com.google.protobuf.AbstractParser<SaveFeedbackRequest>() {
      @java.lang.Override
      public SaveFeedbackRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveFeedbackRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SaveFeedbackRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveFeedbackRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Feedback.SaveFeedbackRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SaveFeedbackResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.SaveFeedbackResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code grpc.SaveFeedbackResponse}
   */
  public  static final class SaveFeedbackResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.SaveFeedbackResponse)
      SaveFeedbackResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveFeedbackResponse.newBuilder() to construct.
    private SaveFeedbackResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveFeedbackResponse() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SaveFeedbackResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Feedback.internal_static_grpc_SaveFeedbackResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Feedback.internal_static_grpc_SaveFeedbackResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Feedback.SaveFeedbackResponse.class, grpc.Feedback.SaveFeedbackResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Feedback.SaveFeedbackResponse)) {
        return super.equals(obj);
      }
      grpc.Feedback.SaveFeedbackResponse other = (grpc.Feedback.SaveFeedbackResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.SaveFeedbackResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Feedback.SaveFeedbackResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.SaveFeedbackResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.SaveFeedbackResponse)
        grpc.Feedback.SaveFeedbackResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Feedback.internal_static_grpc_SaveFeedbackResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Feedback.internal_static_grpc_SaveFeedbackResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Feedback.SaveFeedbackResponse.class, grpc.Feedback.SaveFeedbackResponse.Builder.class);
      }

      // Construct using grpc.Feedback.SaveFeedbackResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Feedback.internal_static_grpc_SaveFeedbackResponse_descriptor;
      }

      @java.lang.Override
      public grpc.Feedback.SaveFeedbackResponse getDefaultInstanceForType() {
        return grpc.Feedback.SaveFeedbackResponse.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Feedback.SaveFeedbackResponse build() {
        grpc.Feedback.SaveFeedbackResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Feedback.SaveFeedbackResponse buildPartial() {
        grpc.Feedback.SaveFeedbackResponse result = new grpc.Feedback.SaveFeedbackResponse(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Feedback.SaveFeedbackResponse) {
          return mergeFrom((grpc.Feedback.SaveFeedbackResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Feedback.SaveFeedbackResponse other) {
        if (other == grpc.Feedback.SaveFeedbackResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Feedback.SaveFeedbackResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Feedback.SaveFeedbackResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.SaveFeedbackResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc.SaveFeedbackResponse)
    private static final grpc.Feedback.SaveFeedbackResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Feedback.SaveFeedbackResponse();
    }

    public static grpc.Feedback.SaveFeedbackResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveFeedbackResponse>
        PARSER = new com.google.protobuf.AbstractParser<SaveFeedbackResponse>() {
      @java.lang.Override
      public SaveFeedbackResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveFeedbackResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SaveFeedbackResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveFeedbackResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Feedback.SaveFeedbackResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckFeedbackExistenceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.CheckFeedbackExistenceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string item_id = 1;</code>
     */
    java.lang.String getItemId();
    /**
     * <code>string item_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getItemIdBytes();

    /**
     * <code>int32 buyer_id = 2;</code>
     */
    int getBuyerId();
  }
  /**
   * Protobuf type {@code grpc.CheckFeedbackExistenceRequest}
   */
  public  static final class CheckFeedbackExistenceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.CheckFeedbackExistenceRequest)
      CheckFeedbackExistenceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckFeedbackExistenceRequest.newBuilder() to construct.
    private CheckFeedbackExistenceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckFeedbackExistenceRequest() {
      itemId_ = "";
      buyerId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckFeedbackExistenceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              itemId_ = s;
              break;
            }
            case 16: {

              buyerId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Feedback.CheckFeedbackExistenceRequest.class, grpc.Feedback.CheckFeedbackExistenceRequest.Builder.class);
    }

    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object itemId_;
    /**
     * <code>string item_id = 1;</code>
     */
    public java.lang.String getItemId() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemId_ = s;
        return s;
      }
    }
    /**
     * <code>string item_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUYER_ID_FIELD_NUMBER = 2;
    private int buyerId_;
    /**
     * <code>int32 buyer_id = 2;</code>
     */
    public int getBuyerId() {
      return buyerId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getItemIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, itemId_);
      }
      if (buyerId_ != 0) {
        output.writeInt32(2, buyerId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getItemIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, itemId_);
      }
      if (buyerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buyerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Feedback.CheckFeedbackExistenceRequest)) {
        return super.equals(obj);
      }
      grpc.Feedback.CheckFeedbackExistenceRequest other = (grpc.Feedback.CheckFeedbackExistenceRequest) obj;

      boolean result = true;
      result = result && getItemId()
          .equals(other.getItemId());
      result = result && (getBuyerId()
          == other.getBuyerId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId().hashCode();
      hash = (37 * hash) + BUYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBuyerId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.CheckFeedbackExistenceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Feedback.CheckFeedbackExistenceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.CheckFeedbackExistenceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.CheckFeedbackExistenceRequest)
        grpc.Feedback.CheckFeedbackExistenceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Feedback.CheckFeedbackExistenceRequest.class, grpc.Feedback.CheckFeedbackExistenceRequest.Builder.class);
      }

      // Construct using grpc.Feedback.CheckFeedbackExistenceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        itemId_ = "";

        buyerId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceRequest_descriptor;
      }

      @java.lang.Override
      public grpc.Feedback.CheckFeedbackExistenceRequest getDefaultInstanceForType() {
        return grpc.Feedback.CheckFeedbackExistenceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Feedback.CheckFeedbackExistenceRequest build() {
        grpc.Feedback.CheckFeedbackExistenceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Feedback.CheckFeedbackExistenceRequest buildPartial() {
        grpc.Feedback.CheckFeedbackExistenceRequest result = new grpc.Feedback.CheckFeedbackExistenceRequest(this);
        result.itemId_ = itemId_;
        result.buyerId_ = buyerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Feedback.CheckFeedbackExistenceRequest) {
          return mergeFrom((grpc.Feedback.CheckFeedbackExistenceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Feedback.CheckFeedbackExistenceRequest other) {
        if (other == grpc.Feedback.CheckFeedbackExistenceRequest.getDefaultInstance()) return this;
        if (!other.getItemId().isEmpty()) {
          itemId_ = other.itemId_;
          onChanged();
        }
        if (other.getBuyerId() != 0) {
          setBuyerId(other.getBuyerId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Feedback.CheckFeedbackExistenceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Feedback.CheckFeedbackExistenceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object itemId_ = "";
      /**
       * <code>string item_id = 1;</code>
       */
      public java.lang.String getItemId() {
        java.lang.Object ref = itemId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getItemIdBytes() {
        java.lang.Object ref = itemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder setItemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = getDefaultInstance().getItemId();
        onChanged();
        return this;
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder setItemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itemId_ = value;
        onChanged();
        return this;
      }

      private int buyerId_ ;
      /**
       * <code>int32 buyer_id = 2;</code>
       */
      public int getBuyerId() {
        return buyerId_;
      }
      /**
       * <code>int32 buyer_id = 2;</code>
       */
      public Builder setBuyerId(int value) {
        
        buyerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buyer_id = 2;</code>
       */
      public Builder clearBuyerId() {
        
        buyerId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.CheckFeedbackExistenceRequest)
    }

    // @@protoc_insertion_point(class_scope:grpc.CheckFeedbackExistenceRequest)
    private static final grpc.Feedback.CheckFeedbackExistenceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Feedback.CheckFeedbackExistenceRequest();
    }

    public static grpc.Feedback.CheckFeedbackExistenceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckFeedbackExistenceRequest>
        PARSER = new com.google.protobuf.AbstractParser<CheckFeedbackExistenceRequest>() {
      @java.lang.Override
      public CheckFeedbackExistenceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckFeedbackExistenceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckFeedbackExistenceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckFeedbackExistenceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Feedback.CheckFeedbackExistenceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckFeedbackExistenceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.CheckFeedbackExistenceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool exists = 1;</code>
     */
    boolean getExists();
  }
  /**
   * Protobuf type {@code grpc.CheckFeedbackExistenceResponse}
   */
  public  static final class CheckFeedbackExistenceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.CheckFeedbackExistenceResponse)
      CheckFeedbackExistenceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckFeedbackExistenceResponse.newBuilder() to construct.
    private CheckFeedbackExistenceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckFeedbackExistenceResponse() {
      exists_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckFeedbackExistenceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              exists_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Feedback.CheckFeedbackExistenceResponse.class, grpc.Feedback.CheckFeedbackExistenceResponse.Builder.class);
    }

    public static final int EXISTS_FIELD_NUMBER = 1;
    private boolean exists_;
    /**
     * <code>bool exists = 1;</code>
     */
    public boolean getExists() {
      return exists_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (exists_ != false) {
        output.writeBool(1, exists_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (exists_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, exists_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Feedback.CheckFeedbackExistenceResponse)) {
        return super.equals(obj);
      }
      grpc.Feedback.CheckFeedbackExistenceResponse other = (grpc.Feedback.CheckFeedbackExistenceResponse) obj;

      boolean result = true;
      result = result && (getExists()
          == other.getExists());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXISTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExists());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Feedback.CheckFeedbackExistenceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Feedback.CheckFeedbackExistenceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.CheckFeedbackExistenceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.CheckFeedbackExistenceResponse)
        grpc.Feedback.CheckFeedbackExistenceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Feedback.CheckFeedbackExistenceResponse.class, grpc.Feedback.CheckFeedbackExistenceResponse.Builder.class);
      }

      // Construct using grpc.Feedback.CheckFeedbackExistenceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        exists_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Feedback.internal_static_grpc_CheckFeedbackExistenceResponse_descriptor;
      }

      @java.lang.Override
      public grpc.Feedback.CheckFeedbackExistenceResponse getDefaultInstanceForType() {
        return grpc.Feedback.CheckFeedbackExistenceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Feedback.CheckFeedbackExistenceResponse build() {
        grpc.Feedback.CheckFeedbackExistenceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Feedback.CheckFeedbackExistenceResponse buildPartial() {
        grpc.Feedback.CheckFeedbackExistenceResponse result = new grpc.Feedback.CheckFeedbackExistenceResponse(this);
        result.exists_ = exists_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Feedback.CheckFeedbackExistenceResponse) {
          return mergeFrom((grpc.Feedback.CheckFeedbackExistenceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Feedback.CheckFeedbackExistenceResponse other) {
        if (other == grpc.Feedback.CheckFeedbackExistenceResponse.getDefaultInstance()) return this;
        if (other.getExists() != false) {
          setExists(other.getExists());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Feedback.CheckFeedbackExistenceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Feedback.CheckFeedbackExistenceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean exists_ ;
      /**
       * <code>bool exists = 1;</code>
       */
      public boolean getExists() {
        return exists_;
      }
      /**
       * <code>bool exists = 1;</code>
       */
      public Builder setExists(boolean value) {
        
        exists_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool exists = 1;</code>
       */
      public Builder clearExists() {
        
        exists_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.CheckFeedbackExistenceResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc.CheckFeedbackExistenceResponse)
    private static final grpc.Feedback.CheckFeedbackExistenceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Feedback.CheckFeedbackExistenceResponse();
    }

    public static grpc.Feedback.CheckFeedbackExistenceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckFeedbackExistenceResponse>
        PARSER = new com.google.protobuf.AbstractParser<CheckFeedbackExistenceResponse>() {
      @java.lang.Override
      public CheckFeedbackExistenceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckFeedbackExistenceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckFeedbackExistenceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckFeedbackExistenceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Feedback.CheckFeedbackExistenceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SaveFeedbackRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SaveFeedbackRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SaveFeedbackResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SaveFeedbackResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CheckFeedbackExistenceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CheckFeedbackExistenceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CheckFeedbackExistenceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CheckFeedbackExistenceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016feedback.proto\022\004grpc\"J\n\023SaveFeedbackRe" +
      "quest\022\017\n\007item_id\030\001 \001(\t\022\020\n\010buyer_id\030\002 \001(\005" +
      "\022\020\n\010feedback\030\003 \001(\010\"\'\n\024SaveFeedbackRespon" +
      "se\022\017\n\007success\030\001 \001(\010\"B\n\035CheckFeedbackExis" +
      "tenceRequest\022\017\n\007item_id\030\001 \001(\t\022\020\n\010buyer_i" +
      "d\030\002 \001(\005\"0\n\036CheckFeedbackExistenceRespons" +
      "e\022\016\n\006exists\030\001 \001(\0102\301\001\n\017FeedbackService\022G\n" +
      "\014SaveFeedback\022\031.grpc.SaveFeedbackRequest" +
      "\032\032.grpc.SaveFeedbackResponse\"\000\022e\n\026CheckF" +
      "eedbackExistence\022#.grpc.CheckFeedbackExi" +
      "stenceRequest\032$.grpc.CheckFeedbackExiste" +
      "nceResponse\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_SaveFeedbackRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_SaveFeedbackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SaveFeedbackRequest_descriptor,
        new java.lang.String[] { "ItemId", "BuyerId", "Feedback", });
    internal_static_grpc_SaveFeedbackResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_SaveFeedbackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SaveFeedbackResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_grpc_CheckFeedbackExistenceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_CheckFeedbackExistenceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CheckFeedbackExistenceRequest_descriptor,
        new java.lang.String[] { "ItemId", "BuyerId", });
    internal_static_grpc_CheckFeedbackExistenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_CheckFeedbackExistenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CheckFeedbackExistenceResponse_descriptor,
        new java.lang.String[] { "Exists", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
